require 'rubygems'
require 'faker'

AIRLINES = [
  ['Aer Lingus', 'EI', 'Terminal 2'],
  ['Aeroflot', 'SU', 'TBIT'],
  ['Aeromexico', 'AM', 'Terminal 2'],
  ['Air Berlin', 'AB', 'TBIT'],
  ['Air Canada', 'AC', 'Terminal 6'],
  ['Air China', 'CA', 'TBIT'],
  ['Air France', 'AF', 'TBIT'],
  ['Air New Zealand', 'NZ', 'TBIT'],
  ['Air Tahiti Nui', 'TN', 'TBIT'],
  ['Alaska Airlines', 'AS', 'Terminal 6'],
  ['Alitalia', 'AZ', 'TBIT'],
  ['All Nippon Airways (ANA)', 'NH', 'TBIT'],
  ['Allegiant Air', 'G4', 'Terminal 5'],
  ['American Airlines', 'AA', 'Terminal 4'],
  ['American Airlines', 'AA', 'Terminal 5'],
  ['American Eagle', 'AA', 'Terminal 4'],
  ['Asiana Airlines', 'OZ', 'TBIT'],
  ['Austrian Airlines', 'OS', 'TBIT'],
  ['Avianca Airlines', 'AV', 'Terminal 3'],
  ['Boutique Airlines', '4B', 'Terminal 6'],
  ['British Airways', 'BA', 'TBIT'],
  ['Cathay Pacific Airways', 'CX', 'TBIT'],
  ['China Airlines', 'CI', 'TBIT'],
  ['China Eastern', 'MU', 'TBIT'],
  ['China Southern', 'CZ', 'TBIT'],
  ['Copa Airlines', 'CM', 'TBIT'],
  ['Copa Airlines', 'CM', 'Terminal 3'],
  ['Delta Airlines', 'DL', 'Terminal 2'],
  ['Delta Airlines', 'DL', 'Terminal 3'],
  ['El Al Israel Airlines', 'LY', 'TBIT'],
  ['Emirates', 'EK', 'TBIT'],
  ['Ethiopian Airlines', 'ET', 'Terminal 6'],
  ['Etihad Airways', 'EY', 'TBIT'],
  ['EVA Air', 'BR', 'TBIT'],
  ['Fiji Airways', 'FJ', 'TBIT'],
  ['Frontier Airlines', 'F9', 'Terminal 5'],
  ['Great Lakes Airlines', 'ZK', 'Terminal 6'],
  ['Hainan Airlines', 'HU', 'TBIT'],
  ['Hawaiian Airlines', 'HA', 'Terminal 5'],
  ['Iberia Airlines', 'IB', 'TBIT'],
  ['InterJet', '4O', 'Terminal 3'],
  ['Japan Airlines', 'JL', 'TBIT'],
  ['Jet Blue', 'B6', 'Terminal 5'],
  ['KLM Royal Dutch Airlines', 'KL', 'TBIT'],
  ['Korean Airlines', 'KE', 'TBIT'],
  ['LATAM', 'LA', 'TBIT'],
  ['Level Airlines', 'IB', 'TBIT'],
  ['LOT Polish', 'LO', 'TBIT'],
  ['Lufthansa', 'LH', 'TBIT'],
  ['Mokulele Airlines', 'MW', 'Terminal 6'],
  ['Norwegian Air Shuttle', 'DY', 'TBIT'],
  ['Philippine Airlines', 'PR', 'TBIT'],
  ['Qantas', 'QF', 'TBIT'],
  ['Qatar Airways', 'QR', 'TBIT'],
  ['Scandanavian Airlines', 'SK', 'TBIT'],
  ['Saudi Arabian Airlines', 'SV', 'TBIT'],
  ['Sichuan Airlines', '3U', 'TBIT'],
  ['Singapore Airlines', 'SQ', 'TBIT'],
  ['Southwest Airlines', 'WN', 'Terminal 1'],
  ['Southwest International', 'WN', 'TBIT'],
  ['Spirit Airlines', 'NK', 'Terminal 5'],
  ['Sun Country', 'SY', 'Terminal 5'],
  ['Swiss International Air Lines Ltd.', 'LX', 'TBIT'],
  ['Thomas Cook Airlines', 'MT', 'Terminal 6'],
  ['Transaero', 'UN', 'TBIT'],
  ['Turkish Airlines', 'TK', 'TBIT'],
  ['United Airlines', 'UA', 'Terminal 7'],
  ['United Airlines', 'UA', 'Terminal 8'],
  ['United Airlines', 'UA', 'Terminal 6'],
  ['United Express', 'UA', 'Terminal 7'],
  ['United Express Airlines', 'UA', 'Terminal 8'],
  ['Virgin America', 'VX', 'Terminal 6'],
  ['Virgin Atlantic', 'VS', 'Terminal 2'],
  ['Virgin Australia', 'VA', 'Terminal 2'],
  ['Volaris', 'Y4', 'Terminal 2'],
  ['West Jet', 'WS', 'Terminal 2'],
  ['WOW Air', 'WW', 'TBIT'],
  ['Xiamen Airlines', 'MF', 'TBIT'],
  ['XL Airways France', 'SE', 'Terminal 6']
]

EXPANSIONS [
  ['TBIT', 'Tom Bradley International Terminal']
]
